spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to nvm10 account ms QA APIs."
  contactDetails:
    name: "John Doe QA"
    email: "john@doeqa.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 555-1235