spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.2"

card:
  message: "Welcome to nvm10 account ms APIs."
  contactDetails:
    name: "John Doe"
    email: "john@doe.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 555-1235